version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 3000
    environment:
      - APP_NAME=web
      - PORT=3000

  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 5000
    environment:
      - APP_NAME=app
      - PORT=5000

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - 80:80
    depends_on:
      - web
      - app
